### ISSUE TITLE
Problem about Reporter

### ISSUE THREAD

**Issue by Hare-Lucius** [ashish-gehani/SPADE#114] opened 2021-06-01 18:21 UTC
I have two problems which I hope you can do me a favour. I use Ubuntu 20.04.
First,  I download SPADE on 20th May, and I encounter a problem that I cannot collect information with Audit and fileIO=true setted. I'm sorry no useful log can be offered in this case because there is no exception.
To be more specific, when I successfully set `add reporter Audit netIO=true, add storage Neo4j database=data` and visit a website, I can find new data stored into Neo4j. So SPADE works well in netIO situation.
But when I successfully set `add reporter Audit fileIO=true, add storage Neo4j database=data` and execute a process which writes a file, no new data can be found in Neo4j. But in fact, system call 'write' should be recored.
Second, after I update SPADE on 1st June, I cannot add reporter any more. 
`add reporter Audit
Adding reporter Audit... failed`
The log is here.
`	at spade.reporter.Audit._launch(Audit.java:307)
	at spade.reporter.Audit.launch(Audit.java:277)
	at spade.core.Kernel.addReporterCommand(Kernel.java:1028)
	at spade.core.Kernel.addCommand(Kernel.java:1192)
	at spade.core.Kernel.executeCommand(Kernel.java:621)
	at spade.core.Kernel$LocalControlConnection.run(Kernel.java:2059)
	at java.base/java.lang.Thread.run(Thread.java:829)

Jun 02, 2021 1:36:16 AM spade.reporter.Audit launch SEVERE: Failed to launch reporter
Jun 02, 2021 1:36:16 AM spade.core.Kernel addReporterCommand SEVERE: Unable to launch reporter
`

**Comment by hassaanirshad** [comment] 2021-06-01 20:18
Duplicate of #113

**Closed by hassaanirshad** 2021-06-01 20:18 UTC
